#!/usr/bin/env bash

export EXPERIMENT_NAME_BASE=${EXPERIMENT_NAME_BASE:-GRPO-DEEPSCALER-Qwen3-30B-A3B-base-MEGATRON-VLLM-FP8-usage-l1-condpct-top8RS-cap2-TIS-C2-16K}
export ROUTER_MISMATCH_RS_MODE=${ROUTER_MISMATCH_RS_MODE:-length_conditional_percentile_top_fraction}
export ROUTER_MISMATCH_RS_FRACTION=${ROUTER_MISMATCH_RS_FRACTION:-0.08}
export ROUTER_MISMATCH_RS_MAX_REJECT_PER_PROMPT=${ROUTER_MISMATCH_RS_MAX_REJECT_PER_PROMPT:-2}
export ROUTER_MISMATCH_RS_LOCAL_WINDOW=${ROUTER_MISMATCH_RS_LOCAL_WINDOW:-256}
export ROUTER_MISMATCH_RS_CENSORED_LENGTH=${ROUTER_MISMATCH_RS_CENSORED_LENGTH:-16384}
export ROUTER_MISMATCH_RS_MIN_CENSORED_COUNT=${ROUTER_MISMATCH_RS_MIN_CENSORED_COUNT:-32}

exec "$(dirname "$0")/run_grpo_qwen3_30b_a3b_expert_distribution_l1_lengthbucket_top8RS_TIS.sh" \
    router.mismatch_rs_max_reject_per_prompt="${ROUTER_MISMATCH_RS_MAX_REJECT_PER_PROMPT}" \
    router.mismatch_rs_local_window="${ROUTER_MISMATCH_RS_LOCAL_WINDOW}" \
    router.mismatch_rs_censored_length="${ROUTER_MISMATCH_RS_CENSORED_LENGTH}" \
    router.mismatch_rs_min_censored_count="${ROUTER_MISMATCH_RS_MIN_CENSORED_COUNT}" \
    "$@"
